---
- name: Install muliple packages package
  hosts: webserver
  become: yes
  tasks:
   - name: install unzip
     apt:
      name: unzip
      state: present
      update_cache: yes
   - name: install tree
     apt:
      name: tree
      state: present
      update_cache: yes
   - name: install httpd 
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: start  httpd 
     service:
      name: apache2 
      state: started 
   - name: install Docker 
     apt:
      name: docker.io
      state: present
      update_cache: yes
   - name: start  docker 
     service:
      name: docker 
      state: started 
       
